### ISSUE TITLE
Version 2.0.0.9 Old mail counted as new

### ISSUE THREAD

**Issue by GrouchyGaijin** [3axap4eHko/OWA-Notifier#27]
I noticed this today after I installed Ubuntu 14.04.
I'm running Chromium and mail that has already been read is still shown as new by the OWA-notifier.

**Comment by 3axap4eHko** [comment]
Welcome here https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug

**Comment by LunarLanding** [comment]
Hi, I thought I had the same problem, but it turned out to be non-read deleted mail.

**Comment by 3axap4eHko** [comment]
No old version support
