### ISSUE TITLE
Go to OWA with one click

### ISSUE THREAD

**Issue by rastarck** [3axap4eHko/OWA-Notifier#28]
Great extension! I love it already!

Something that would enhance my experience would be to automatically open OWA in an existing tab (or new tab if OWA isn't open) when you click on the extension. Currently, it drops down a list of accounts and you have to click the account to switch tabs.

Additionally, if you could emulate the "Checker Plus for Gmail" options this plugin would be just about perfect.

Thanks!

**Comment by 3axap4eHko** [comment]
What is behavior should be if you have unread mails on one more accounts?

**Comment by yura121** [comment]
May be go to in one click if in the list only one account?

**Comment by yura121** [comment]
And open OWA in if clicked on the mouse middle button?
