### ISSUE TITLE
Skip reload if OWA Tab already opened.

### ISSUE THREAD

**Issue by maxgrass** [3axap4eHko/OWA-Notifier#30]
Microsoft updates the mail page in real time, so if an email is received it appears on the page.
OWA-Notifier "opens" the Tab if it's not opened and RELOADS this Tab if it has already been opened.
I think there is no need to refresh already opened tab, just switch to this tab (on new email popup click).

**Comment by 3axap4eHko** [comment]
In the case when user use old version of OWA (like a 2010) or light version, the page with the emails is not updates automatically and should be reloaded

**Comment by maxgrass** [comment]
A check box in the options could make sense, because it's a real use case. Now popup's "click" functionality is quite useless, because instead of reading a new email by jumping to the tab, I have to wait until it reloads.

![reload_checkbox](https://cloud.githubusercontent.com/assets/169885/11907507/c0d50d50-a5d4-11e5-92a4-bb138f6ff53a.png)
