### ISSUE TITLE
Wrong unread emails number with multiple accounts

### ISSUE THREAD

**Issue by andreamannelli** [3axap4eHko/OWA-Notifier#32]
When multiple email accounts are configured the number of unread emails is wrong: it seems to be the sum of the unread emails multiplied by the number of accounts.
see attached screenshot:
- 2 accounts
- first account has 7 unread emails
- second account has no unread emails
- owa-notifier shows total of 14 unread emails and 7 unread emails for each account

![owa-notifier-wrong-emails-number](https://cloud.githubusercontent.com/assets/8733552/4230641/22e159a6-3987-11e4-8510-3b86f57ba330.png)

**Comment by 3axap4eHko** [comment]
Welcome here https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug

**Comment by andreamannelli** [comment]
The version is 2.1.1.1
There's no errors in the logs

**Comment by 3axap4eHko** [comment]
Do you have this issue in new version?

**Comment by 3axap4eHko** [comment]
Fixed in 3.0.1.7
