### ISSUE TITLE
Calendar notifications

### ISSUE THREAD

**Issue by rvadlam1** [3axap4eHko/OWA-Notifier#34]
As the title says it, calendar notification like the unread/new email notifications.

**Comment by Riuujin** [comment]
+1 this would be really great and handy to have

**Comment by lnsb** [comment]
+1 This would help a lot since in my case it is very important not to miss meetings :)

**Comment by nakedhitman** [comment]
+1 this feature would rock my socks.

**Comment by jozef3d** [comment]
+1 please add this this would also rock my socks and my pants!

**Comment by boesing** [comment]
+1

**Comment by oliveirajota** [comment]
+1. It would be great

**Comment by tonytcb** [comment]
+1

**Comment by 3axap4eHko** [comment]
Feature implemented in version 2.1.x
