### ISSUE TITLE
Notification Timer

### ISSUE THREAD

**Issue by wbhampton** [3axap4eHko/OWA-Notifier#37]
It appears that the notification timer does not work i'm running windows 7 pro the pop up disappears after about 30 seconds reguradelss if you have all zeros or 48 hours

**Comment by marc2800** [comment]
Yes me too. I have the same problem !

**Comment by marc2800** [comment]
Personally I solve it by using a second notification without time limit. I add this code in exchange.js. 
And now I have a notification of 10 seconds and another static. I need to clic to close the second.

**Comment by 3axap4eHko** [comment]
Welcome here https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug

**Comment by 3axap4eHko** [comment]
Closed due to lack of details
