### ISSUE TITLE
Error E449

### ISSUE THREAD

**Issue by marc2800** [3axap4eHko/OWA-Notifier#39]
Hi, 
I have install OWA Notifier and configure it but now I have "e449" in my icon. 

Here is my configuration : 
![error449](https://cloud.githubusercontent.com/assets/10939280/6125543/63900c92-b117-11e4-9143-762741560342.png)

If somebody can help me.

Thank you in advance !

**Comment by marc2800** [comment]
I replace /owa by /EWS in Exchange Web Service and now in the console the POST method status has status : 200 and give an answer like that : 
![image](https://cloud.githubusercontent.com/assets/10939280/6127333/f1d121b4-b129-11e4-9108-0e291c817b3d.png)

But my icon always doesn't show me 3 unread mail. 

If somebody can help me

**Comment by marc2800** [comment]
Now it work if i select "All Folder" to check. But it doesn't show me the good number of email. I have 8 unread mails and it appears more than 100.

**Comment by 3axap4eHko** [comment]
Hi!
Unfortunetly I can't help you with mails count, but you should check root
folder and all nested folders.

2015-02-11 13:20 GMT+03:00 marc2800 <notifications@github.com>:

> Now it work if i select "All Folder" to check. But it doesn't show me the
> good number of email. I have 8 unread mails and it appears more than 100.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/3axap4eHko/OWA-Notifier/issues/39#issuecomment-73859567>
> .
>



-- 

*Best Regards,*
*Ivan Zakharchenko*

 <http://www.zend.com/en/yellow-pages#show-ClientCandidateID=ZEND022406>

*Habr: *3axap4eHko <http://habrahabr.ru/users/3axap4ehko/>
*linked in:* 3axap4eHko <http://www.linkedin.com/in/3axap4ehko>
*GitHub CV**:** 3axap4eHko <http://3axap4ehko.github.com/CV/>*
*skype: battlebit*

*e-mail: 3axap4eHko@gmail.com <3axap4eHko@gmail.com>*

**Comment by marc2800** [comment]
Ok. Thank you for the answer ! Now it works "All Folder" but not now for the Inbox.

**Comment by marc2800** [comment]
I post my configuration with Office 365 Business if this post can help somebody to configure it  : 
![configuration](https://cloud.githubusercontent.com/assets/10939280/6183104/c2b59738-b350-11e4-9b33-3959be0765d3.png)

**Comment by marc2800** [comment]
Hi Ivan, I work on your plugin, and I found something for people doesn't have the mail box in english.
Personnaly my my mail box is in french and the reponse XML file the display name is "<t:DisplayName>Boîte de réception</t:DisplayName>" and not "Inbox". 
So I modify my version in my company but if you want add that in your next version I can send you you the multilanguage code. 
Best Regards 
Marc
Date: Wed, 11 Feb 2015 02:23:55 -0800
