### ISSUE TITLE
Just doesn't work

### ISSUE THREAD

**Issue by vavileno** [3axap4eHko/OWA-Notifier#41]
Has been setup all urls, usernames etc.
No any notifications.

**Comment by 3axap4eHko** [comment]
Welcome here https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug

**Comment by candyshien** [comment]
I got the same problem, unable to use on Chrome Version 44.0.2403.157 m after setup all.
But able to work on Firefox.

**Comment by Binusz** [comment]
May be my problem is related this issue. I want to reset chrome setting. After that I start to setup new account at this extension. I have been also setup all url username for account, extension just show a progress bar very limited moment. (less than a second)

There is no red console message. However, there is a response from mail server at the Network Tab. Here is Screenshot;
![screen shot 2015-08-26 at 19 45 16](https://cloud.githubusercontent.com/assets/2385327/9499976/53a87cce-4c2b-11e5-83f9-5292803bd795.png)



My Configuration: Mac OS X 10.10.5, Chrome 45.0.2454.46 beta (64-bit)

**Comment by Binusz** [comment]
ı just realize that i was writing wrong Exchange Server URL :)
