### ISSUE TITLE
Custom folder to check selection possibility, custom regional settings, no Inbox

### ISSUE THREAD

**Issue by j-martyn** [3axap4eHko/OWA-Notifier#42]
I have no `Inbox` folder in my account because of regional language settings on server. I have `Входящие` :)
I managed that issue for myself by changing the 
```js
callback($(data).find('DisplayName:contains("Inbox")').parent()...;
```
to
```js
callback($(data).find('DisplayName:contains("Входящие")').parent()...;
```
in [/src/js/exchange.js:245](https://github.com/3axap4eHko/OWA-Notifier/blob/535660d95d1bc39f94da62d972c6b49952c7a57c/src/js/exchange.js#L245), but it's a dirty hack, of course.

It would be great to add ability of adding custom folders to check by entering their name or, even better, by getting all folders list from Exchange, if it's possible.

**Comment by 3axap4eHko** [comment]
Fixed
