### ISSUE TITLE
No notification if "Check folder" been set to "All folders" on 2.1.1.1

### ISSUE THREAD

**Issue by Cappuccin0** [3axap4eHko/OWA-Notifier#43]
Every things works perfectly before updating the extension to latest ver (or latest several versions).

Steps for reproducing:
1. make a unread mail in the inbox
2. if the settings is checking all folders, and there's no notification or icon change (already wait long enough)
3. switch settings to checking inbox only, the notification pop out immediately, as well as the icon change.

There's no error messages in console output in background page. The issue behavior the same on ubuntu and win7 with latest Chrome.

**Comment by 3axap4eHko** [comment]
Do you have this issue in new version?

**Comment by Cappuccin0** [comment]
Seems still can see the same issue in the latest build (2.0.1.0 - 3.0.1.6)...

I made a local package based on 2.0.0.9 and everything works fine. (commit 535660d seems to be the last one working properly)

**Comment by yura121** [comment]
It seems that the issue is not reproduced since version 3.0.2.5. I've completed the steps, but the issue does not appear.

**Comment by yura121** [comment]
But may be need to rename 'Root' to 'All folders'.

**Comment by 3axap4eHko** [comment]
No support for old version
