### ISSUE TITLE
Accounts extra details not work

### ISSUE THREAD

**Issue by Binusz** [3axap4eHko/OWA-Notifier#46]
Account Settings tap can easily switchable. When i try to open more settings initially, it does not work. However i try to add account and cancel the adding account then i try to select more button, it works.

This bug reproducible. 

![screen shot 2015-08-19 at 08 57 42](https://cloud.githubusercontent.com/assets/2385327/9349596/eba54b6e-4650-11e5-9737-1e4a3b607d8c.png)

**Comment by 3axap4eHko** [comment]
Provide please information about your OS and Chrome version for reproduce.

**Comment by Binusz** [comment]
Mac OS X 10.10.5 
Chrome Version 45.0.2454.37 beta (64-bit)


I also attach Chrome inspect screenshot

First opened.
![screen shot 2015-08-19 at 10 32 16](https://cloud.githubusercontent.com/assets/2385327/9351001/3dc9343e-465e-11e5-8a1b-ed9857b60aef.png)

After the reload page. (without select or do anything)
![screen shot 2015-08-19 at 10 35 23](https://cloud.githubusercontent.com/assets/2385327/9350999/3abb554c-465e-11e5-9394-8816dd578856.png)

**Comment by 3axap4eHko** [comment]
Did you tried reload page after adding new account? I found that problem in used framework Material-Design Lite, after generation new row in the account table.

**Comment by Binusz** [comment]
No, i didn't. 
I have already an account. After the extension update, i just want to discover what's new. 

Step by step; 
1- I get notified about extension update. 
2- clicked on button where located in google setting button and other buttons. 
3- clicked people icon in the floating window.
4- was opened OWA Notifier as new tap page.
5- after all, i try to click on settings button on related account. (1st screenshoot)

when i clicked, there is nothing happen. When i just reload that page, the settings button started to work. (appears mini menu).

**Comment by 3axap4eHko** [comment]
Got it, I investigate the issue and found that this is problem of Material Design Lite framework. I will fix this issue soon.
Thank you for your participation.

**Comment by 3axap4eHko** [comment]
Fixed in 3.0.1.7

**Comment by Binusz** [comment]
Yeap :D 
it is fixed.
