### ISSUE TITLE
Can't set time correctly

### ISSUE THREAD

**Issue by rodbagni** [3axap4eHko/OWA-Notifier#47]
I'm trying to set new values for times (Update interval and Display time). When I set 00h for hour, it actually stores 23h. Example: trying to set "Update interval" to 00:05:00 results in 23:05:00.
![set_update_interval](https://cloud.githubusercontent.com/assets/13869449/9356600/4f35472c-4658-11e5-9275-c650b54f4a55.png)
![update_interval_result](https://cloud.githubusercontent.com/assets/13869449/9356601/4f4f3448-4658-11e5-91b7-07aab13da6cf.png)

OWA-notifier version: 3.0.1.1
Chrome version: Version 43.0.2357.130 Ubuntu 14.04 (64-bit)

**Comment by 3axap4eHko** [comment]
I'll fix this soon.
Thank you for your participation!

**Comment by 3axap4eHko** [comment]
Fixed in 3.0.1.6
