### ISSUE TITLE
does not indicate when stored password is not accepted

### ISSUE THREAD

**Issue by geza-kiss** [3axap4eHko/OWA-Notifier#49]
Previously it seemed to me that the extension does not work.
But it turned out that it works, only my password was not correct (I didn't update it after a password change). It would be great if the extension showed that somehow. 
(The instructions below helped, as the background.html page for the extension showed in red that there was an authentication problem.)

I am using the latest extension (as of 08/20/2015), on openSUSE and Google Chrome.

**Comment by 3axap4eHko** [comment]
https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug

**Comment by geza-kiss** [comment]
Sorry, it was my fault. (Haven't updated the password. The instructions helped, as looking at the errors showed what the problem was.)

**Comment by 3axap4eHko** [comment]
Awesome! I'll implement connection data testing before saving.

**Comment by 3axap4eHko** [comment]
Implemented in 3.0.2.1
