### ISSUE TITLE
[SOLVED] Options not accepted

### ISSUE THREAD

**Issue by stephenhogan** [3axap4eHko/OWA-Notifier#55]
Hi,

I am trying to create an account based on my Office365 E3 Plan Exchange Online settings, but after the settings are inserted in the Options for OWA Notifier, and I click OK, I see a progress bar momentarily, but the account is not created, the options screen stays up, and no account is created.

I am using the following settings, but I have tried many different types of Exchange Server URL, not only in the pic below, but also https://outlook.office365.com/owa/?realm=mila.ie and a few others.

![capture](https://cloud.githubusercontent.com/assets/8396606/9680326/02f9faae-52ee-11e5-9c81-71e9c0de878f.PNG)

No errors seen in background.html.

I am seeing errors with F12 though...

![capture](https://cloud.githubusercontent.com/assets/8396606/9680756/074a2770-52f1-11e5-81d9-d7cfaa2fea5b.PNG)

I have no issues using OWA or Outlook 2013 at this time.

![capture](https://cloud.githubusercontent.com/assets/8396606/9680826/91f91b6a-52f1-11e5-8fa1-149f802f0118.PNG)

Windows 7 SP1 64-bit, patched ot last months' updates.

Thanks, in advance.

Stephen

**Comment by stephenhogan** [comment]
![capture](https://cloud.githubusercontent.com/assets/8396606/9680805/717bc96e-52f1-11e5-8f6b-7f98b4fe35be.PNG)

**Comment by 3axap4eHko** [comment]
It seems like you have an issue with connection to the exchange web server. Check your url.

**Comment by stephenhogan** [comment]
No problem with the URL.

I retried and could see GlassWire detecting OWAN and creating a firewall rule - I should have guessed!

Anyway, seems to be working now - thank you very much!

Case closed.


Regards,
Stephen
