### ISSUE TITLE
Delete popup doesn't close on OK click

### ISSUE THREAD

**Issue by j-martyn** [3axap4eHko/OWA-Notifier#63]
TC:

1. Two accounts must be created.
2. Click on delete button for first account.
3. Popup `Are you sure you want to delete record?` is displayed.
4. Click OK.

Expected result: Account is deleted and popup is closed
Actual result: Account has been deleted and **popup isn't closed**. 

5. If you don't realize that account has been deleted you clicking OK again and second account is being deleted too.

**Comment by yura121** [comment]
This issue fixed with commit 0415e79
