### ISSUE TITLE
Only works when "Folder" is set to "Inbox"

### ISSUE THREAD

**Issue by GranBurguesa** [3axap4eHko/OWA-Notifier#65]
When it's set to the default, "root", I just get the red exclamation mark. Switching to "Inbox" makes everything work well.

Also, the help page mentions being able to find a log file but the instructions seem out of date.

**Comment by 3axap4eHko** [comment]
https://github.com/3axap4eHko/OWA-Notifier/wiki/4.-How-to-report-a-bug
