### ISSUE TITLE
Option to disable analytics

### ISSUE THREAD

**Issue by GranBurguesa** [3axap4eHko/OWA-Notifier#66]
It would be nice to be able to disable Google Analytics tracking.

**Comment by 3axap4eHko** [comment]
Hi!
Google Analytics not enabled and libraries and premissions for this feature will be removed soon

**Comment by GranBurguesa** [comment]
Hi,
I'm glad to hear this has been removed. Will there be a release with the permission removed any time soon? I'm trying to get this set up with our company machines and the IT guy is scared of analytics for whatever reason.
