### ISSUE TITLE
"mark as read" button in popup

### ISSUE THREAD

**Issue by maxgrass** [3axap4eHko/OWA-Notifier#73]
[enh]
![2015-11-23 09_00_44-theobald ecs kui_scripts_kendo_theobald kscenario js cloudframework - brackets](https://cloud.githubusercontent.com/assets/169885/11331887/c45e125a-91c0-11e5-981d-7d76d02b96a3.png)

**Comment by 3axap4eHko** [comment]
Implemented in version 4.x
