### ISSUE TITLE
After 4.0.0.1 update, seems to not work anymore

### ISSUE THREAD

**Issue by renolc** [3axap4eHko/OWA-Notifier#74]
Extension auto updated to 4.0.0.1, and now there seem to be quite a few issues. It doesn't notify anymore, the options page has overlapping fields, and the accounts tab is completely blank.

**Browser:** Chrome 47.0.2526.106 (64-bit)
**OS:** OSX Yosemite 10.10.5
**General tab:**
<img width="966" alt="screenshot 2015-12-23 10 38 06" src="https://cloud.githubusercontent.com/assets/4680221/11979429/50d37ed4-a961-11e5-925b-fe3625ca0544.png">
**Accounts tab:**
<img width="949" alt="screenshot 2015-12-23 10 38 49" src="https://cloud.githubusercontent.com/assets/4680221/11979438/5fa698ba-a961-11e5-9aaf-33c7a3b91620.png">
**background.html errors:**
<img width="720" alt="screenshot 2015-12-23 10 36 38" src="https://cloud.githubusercontent.com/assets/4680221/11979406/12cddfbc-a961-11e5-99ff-63141d0ce906.png">
**console errors on options page:**
<img width="669" alt="screenshot 2015-12-23 10 37 20" src="https://cloud.githubusercontent.com/assets/4680221/11979416/2e98a754-a961-11e5-84d6-3b487a59d267.png">

**Comment by leskeg** [comment]
Same here
Browser: Chromium Version 47.0.2526.106 (64-bit)
OS: Archlinux

**Comment by Binusz** [comment]
+1 
But, all account info reseted today.

**Comment by 3axap4eHko** [comment]
Updated to 4.0.0.3. The issue depends with user data migration to the new version. Currently almost issues are fixed by reset user data.
