### ISSUE TITLE
Doesn't work after recent updates. No way to add accounts

### ISSUE THREAD

**Issue by jiade** [3axap4eHko/OWA-Notifier#79]
Ok. I would say the pop-up issue was fixed. However, another problem makes it not usable. The Accounts page in the settings is blank and there is no way to add account. And my previous setup account seems also to be lost. The issue seems related to display or somehow, because on the General tab, the texts are overlapping with each other and is not readable.
My Chrome version is Version 47.0.2526.106 (64-bit)
![image](https://cloud.githubusercontent.com/assets/9125195/12081909/7c72338e-b256-11e5-8082-b8b2b693e420.png)
![image](https://cloud.githubusercontent.com/assets/9125195/12081916/94ecec88-b256-11e5-8c49-6d053e923daf.png)

**Comment by 3axap4eHko** [comment]
Try to reinstall extension and follow this steps https://github.com/3axap4eHko/OWA-Notifier/wiki/3.-How-to-report-a-bug
