### ISSUE TITLE
Can't add account

### ISSUE THREAD

**Issue by nostop8** [3axap4eHko/OWA-Notifier#80]
Lately, probably after latest update, I'm not able to create new account and old stopped working.
Anyway, when I try to add new account, fill in all the fields, press OK button, but it does not do anything and no information is provided on the screen. When I check console, I see error code "449 OK" and following response body "The custom error module does not recognize this error."
Not sure if it is generated by our server or by your extension later. The explanation of this strange Microsoft error (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) does not make much sense to me. Probably this is some additional security stuff?
Please, find below versions + request/response information, but without server url and my account details of course.

***Extension: 4.0.0.5
Windows: 10
Chrome: 47.0.2526.106 m
Errors: 449 OK***

***General***
Request URL:https://mylogin:mypass@mydomain/owa/Exchange.asmx
Request Method:POST
Status Code:449 OK
Remote Address:***

***Request Headers:***

Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en,uk;q=0.8,ru;q=0.6,nl;q=0.4,pt-BR;q=0.2,pt;q=0.2,en-US;q=0.2
Cache-Control:no-cache
Connection:keep-alive
Content-Length:686
Content-Type:text/xml
Cookie: ...
Host:ex2013.symphony-solutions.eu
Origin:chrome-extension://hldldpjjjagjfikfknadmnnmpbbhgihg
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

***Request Payload***

`<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
    <soap:Body>
        <m:GetFolder>
            <m:FolderShape>
                <t:BaseShape>AllProperties</t:BaseShape>
            </m:FolderShape>
            <m:FolderIds>
                <t:DistinguishedFolderId Id="msgfolderroot"/>
            </m:FolderIds>
        </m:GetFolder>
    </soap:Body>
</soap:Envelope>`

***Response Headers***
Cache-Control:private
Content-Length:54
Content-Type:text/html
Date:Mon, 04 Jan 2016 11:29:22 GMT
request-id:...
Server:Microsoft-IIS/8.5
Set-Cookie:...
X-AspNet-Version:4.0.30319
X-BackEnd-Begin:2016-01-04T13:29:22.570
X-BackEnd-End:2016-01-04T13:29:22.585
X-BEServer:EX2013
X-CalculatedBETarget:...
X-Content-Type-Options:nosniff
X-DiagInfo:EX2013
X-FEServer:EX2013
X-OWA-DiagnosticsInfo:16;0;0
X-OWA-MinimumSupportedOWSVersion:V2_6
X-OWA-OWSVersion:V2_8
X-OWA-Version:15.0.847.32
X-Powered-By:ASP.NET
X-UA-Compatible:IE=EmulateIE7

***Response Body***
The custom error module does not recognize this error.

**Comment by 3axap4eHko** [comment]
Hi! Just reinstall extension and change for EWS Server URL from
'https://mylogin:mypass@mydomain/**owa**/Exchange.asmx'
to
'https://mylogin:mypass@mydomain/**ews**/Exchange.asmx'

**Comment by nostop8** [comment]
Alright! Thanks a lot! I should have read this first https://github.com/3axap4eHko/OWA-Notifier/wiki/2.-How-to-configure . Sorry.
