### ISSUE TITLE
Won't allow account to be added

### ISSUE THREAD

**Issue by dbfun** [3axap4eHko/OWA-Notifier#90]
Extension: Outlook Web Access notifier 4.0.0.5
OS: Ubuntu 14.04
Chromium: Версия 48.0.2564.116 Ubuntu 14.04 (64-bit)
Errors: No, see screenshot
Exchange server use https, with untrust SSL, but I accept it for use during this session
https://dl.dropboxusercontent.com/u/65261445/shot.png

**Comment by 3axap4eHko** [comment]
Hi,
Your exchange server url is: `https://mail.iek.ru/ews`
