### ISSUE TITLE
Added Account deleted by itself and all settings are being resetted

### ISSUE THREAD

**Issue by Binusz** [3axap4eHko/OWA-Notifier#91]
Extension:  4.0.0.5
Mac : 10.11.4
Chrome:  50.0.2661.49 beta (64-bit)

I am not sure but this problem appear with Chrome 50 update. I successfully add account and i can reach my OWA by extension. however, unreaded email count sometimes display wrong number or it might be stuck on old number.

After a long time, i realize that the my account info and extension settings are being resetted.

**Comment by chickenSandwich** [comment]
Verified Chrome Version 50.0.2661.75 m (64-bit) (Windows 7 64bit)
Steps for verification:
Open Chrome
Add Account
Exit Chrome (ensure all processes have closed)
Open Chrome
Observed behavior: The account you created is no longer presented

**Comment by sdecima** [comment]
I can see the exact same behavior in Chrome Versión 50.0.2661.75 (64-bit) (Arch Linux 64bit)

**Comment by lucazade** [comment]
same here on archlinux and chrome 50

**Comment by paulthiggins** [comment]
same here on Ubuntu and Chrome 50

**Comment by grit96** [comment]
I have the same issue on ChromeOS 50

**Comment by mc-lemon** [comment]
Same here
- Chrome 50.0.2661.87
- Win 10

**Comment by bartod** [comment]
same here
Win 8.1
Chrome 50.0.2661.87 m
OWA notifier 4.0.0.5

**Comment by celinew1221** [comment]
Had the same issue with Ubuntu Mate 15.04 and Chrome 50

**Comment by ratazzip** [comment]
Same issue.  Account successfully added, and confirmed working; disappears after Chrome is restarted.

Ubuntu 16.04 LTS 64-bit
Chrome 50.0.2661.94 (64-bit)
Outlook Web Access notifier 4.0.0.5

**Comment by fitigre38** [comment]
Hello,

Same issue 

El Capitan 10.11.4
Chrome 50.0.2661.94 (64-bit)
Outlook Web Access notifier 4.0.0.5

**Comment by jiade** [comment]
Same issue here.
Windows 7 and 8.1, Chrome Version 50.0.2661.87 (64-bit), OWA notifier 4.0.0.5

**Comment by bszen27** [comment]
Same issue.

**Comment by jns0987654321** [comment]
Same Issue. Seems to have started with chrome 50 update.

**Comment by mveiga** [comment]
Same problem happening
Chrome: Version 50.0.2661.94 (64-bit)
Outlook Web Access notifier Version: 4.0.0.5
OS: Fedora 22

**Comment by 3axap4eHko** [comment]
Unfortunately I don't have an OWA account and can't fix this. If somebody can provide me this one it would be grateful :bowtie:

**Comment by sdecima** [comment]
@3axap4eHko this is not a problem with the accounts per se, the extension is not saving anything.
You can try setting the `Update interval` or `Notification Live time` fields, restart Chrome, and you can see that both settings are reset to 00:00:00.
The same happens to the accounts, the config is reset after a restart.

**Comment by olmanrus** [comment]
Same issue with Ubuntu 14.04 and Chrome 50

**Comment by fitigre38** [comment]
Do you know an other solution for OWA notifications ?
Thanks
Philippe

**Comment by DesireeZach** [comment]
The problem I keep having is that OWA keeps forgetting or deleting my account from the extension. It is getting VERY ANNOYING ! ! ! ! ! !

**Comment by 3axap4eHko** [comment]
@sdecima Appreciate for the details! It helps me!

**Comment by 3axap4eHko** [comment]
This issue is affected by removed `Object.observe` method. Instead of this method `Proxy` class should be used, but this class available only in the newest chrome versions. Therefore after the fix this issue all old version browsers will be unable to use this extension.

**Comment by dustinsharp** [comment]
I'm having the same issue.

**Comment by 3axap4eHko** [comment]
Fixed at 4.0.0.7 version
