### ISSUE TITLE
Forgets my school account !

### ISSUE THREAD

**Issue by DesireeZach** [3axap4eHko/OWA-Notifier#94]
The only account I put on the OWA Notifier is my school account. I am not really sure when it deletes my account, like I will go to check my email and I 8 ( more or less, this has happened multiple times ) unread emails. So when I click on the extension to see if it is set up or not, the email will no longer show, which makes me have to go and re-set up the email all of the time. IT IS SOOO ANNOYING !!!!!!!!! 
Any and all help would be appreciated. Thank you for your time.

**Comment by grit96** [comment]
Duplicate of #91
